openapi: 3.1.0
info:
  title: HKUST API
  version: 1.0.0
servers:
  - url: https://w5.ab.ust.hk/msapi
security:
  - bearerAuth: []
paths:
  /token/request:
    post:
      summary: Request a temporary access token
      tags:
        - Authentication
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        description: Temporary access token
              examples:
                example: # providing an example
                  value:
                    access_token: "temporary_token_123"

  /api/getInfo:
    get:
      summary: Get library information
      tags:
        - Library
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      category:
                        type: string
                      areas:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            area_name:
                              type: string
                            open_time:
                              type: string
                            close_time:
                              type: string
                            area_sort_order:
                              type: integer
                            calendar_link:
                              type: string
                            rooms:
                              type: array
                              items:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  room_name:
                                    type: string
                                  capacity:
                                    type: string
                                  custom_html:
                                    type: string
                                  room_sort_order:
                                    type: integer
                                  bookable_class:
                                    type: string
                                  calendar_link:
                                    type: string
              examples:
                example:
                  value:
                    status: "success"
                    data:
                      category: "LIBRARY"
                      areas:
                        - id: "8"
                          area_name: "LC Study Rooms"
                          open_time: "00:00"
                          close_time: "00:00"
                          area_sort_order: 2
                          calendar_link: "https://lbbooking.hkust.edu.hk/calendar/week.php?area=8"
                          rooms:
                            - id: "57"
                              room_name: "LC-01"
                              capacity: "7"
                              custom_html: "http://library.ust.hk/map/lc-01"
                              room_sort_order: 19
                              bookable_class: "|POSTGRADUATE|RESEARCH POSTGRADUATE|TAUGHT POSTGRADUATE|UNDERGRADUATE|"
                              calendar_link: "https://lbbooking.hkust.edu.hk/calendar/week.php?room=57"

  /api/getMySchedule:
    get:
      summary: Get my booked rooms
      tags:
        - Booking
      parameters:
        - in: query
          name: token
          schema:
            type: string
          required: true
          description: Temporary access token
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      numEntry:
                        type: integer
                      bookings:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            name:
                              type: string
                            room_id:
                              type: string
                            start_time:
                              type: integer
                              format: int64
                              description: Unix timestamp
                            end_time:
                              type: integer
                              format: int64
                              description: Unix timestamp
                            type:
                              type: string
                            create_by:
                              type: string
                            description:
                              type: string
                            ical_uid:
                              type: string
                            userclass:
                              type: string
                            start_time_YYYYMMDD:
                              type: string
                            start_time_hhmm:
                              type: string
                            end_time_YYYYMMDD:
                              type: string
                            end_time_hhmm:
                              type: string
              examples:
                example:
                  value:
                    status: "success"
                    data:
                      numEntry: 1
                      bookings:
                        - id: "0000000"
                          name: "CHAN Tai Man"
                          room_id: "76"
                          start_time: 1672531200
                          end_time: 1672549200
                          type: "U"
                          create_by: "yourmum"
                          ical_uid: "yourmum@lbbooking.hkust.edu.hk"
                          userclass: "UNDERGRADUATE"
                          start_time_YYYYMMDD: "20240101"
                          start_time_hhmm: "0000"
                          end_time_YYYYMMDD: "20240101"
                          end_time_hhmm: "2300"

  /api/getSessionsByDay:
    get:
      summary: Get room sessions for a day
      tags:
        - Booking
      parameters:
        - in: query
          name: area
          schema:
            type: string
          required: true
          description: Area ID
        - in: query
          name: year
          schema:
            type: integer
            format: int32
          required: true
        - in: query
          name: month
          schema:
            type: integer
            format: int32
          required: true
        - in: query
          name: day
          schema:
            type: integer
            format: int32
          required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      rooms:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                            room_name:
                              type: string
                            capacity:
                              type: string
                            custom_html:
                              type: string
                            booking_link:
                              type: string
                            calendar_link:
                              type: string
                            start_date:
                              type: string
                            end_date:
                              type: string
                            sessions:
                              type: array
                              items:
                                type: object
                                properties:
                                  start_time:
                                    type: integer
                                    format: int64
                                    description: Unix timestamp
                                  start_time_YYYYMMDD:
                                    type: string
                                  start_time_hhmm:
                                    type: string
                                  end_time:
                                    type: integer
                                    format: int64
                                    description: Unix timestamp
                                  end_time_YYYYMMDD:
                                    type: string
                                  end_time_hhmm:
                                    type: string
                                  status:
                                    type: string
              examples:
                example:
                  value:
                    status: "success"
                    data:
                      rooms:
                        - id: "11"
                          room_name: "1-352"
                          capacity: "8"
                          custom_html: "http://library.ust.hk/map/1352"
                          booking_link: "https://lbbooking.hkust.edu.hk/calendar/week.php?year=2024&month=10&day=31&room=11&area=3"
                          calendar_link: "https://lbbooking.hkust.edu.hk/calendar/week.php?year=2024&month=10&day=31&room=11&area=3"
                          start_date: "20241031"
                          end_date: "20241031"
                          sessions:
                            - start_time: 1730304000
                              start_time_YYYYMMDD: "20241031"
                              start_time_hhmm: "00:00"
                              end_time: 1730332800
                              end_time_YYYYMMDD: "20241031"
                              end_time_hhmm: "08:00"
                              status: "closed"
  /api/entry:
    delete:
      summary: Cancel a booking
      tags:
        - Booking
      parameters:
        - in: query
          name: id
          schema:
            type: string
          required: true
          description: Booking ID
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
              examples:
                example:
                  value:
                    status: "success"

    post:
      summary: Book a room
      tags:
        - Booking
      parameters:
        - in: query
          name: area
          schema:
            type: string
          required: true
          description: Area ID
        - in: query
          name: room
          schema:
            type: string
          required: true
          description: Room ID
        - in: query
          name: year
          schema:
            type: integer
            format: int32
          required: true
        - in: query
          name: month
          schema:
            type: integer
            format: int32
          required: true
        - in: query
          name: day
          schema:
            type: integer
            format: int32
          required: true
        - in: query
          name: hour
          schema:
            type: integer
            format: int32
          required: true
        - in: query
          name: min
          schema:
            type: integer
            format: int32
          required: true
        - in: query
          name: duration
          schema:
            type: integer
            format: int32
          required: true
          description: Duration in minutes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      ical_uid:
                        type: string
              examples:
                example:
                  value:
                    status: "Success"
                    data:
                      id: "someBookingId"
                      ical_uid: "someUID"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
